defaults:
  - _self_
  - models: MobileNetV2
  - optims: adam
  - losses: bce
  - activation_fn: sigmoid
  - augmentations: default
  - preprocessing: default

hyperparams:
  val_split: 0.25
  seed: 777
  n_epochs: 20
  lr: 0.5e-4
  batch_size: 12